version: '3'

services:
  user-postgresql:
    image: 'bitnami/postgresql:15.3.0'
    ports:
      - 15432:5432
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=very-secure-password
      - POSTGRESQL_DATABASE=user_db


  order-postgresql:
    image: 'bitnami/postgresql:15.3.0'
    ports:
      - 25432:5432
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=very-secure-password
      - POSTGRESQL_DATABASE=order_db


  shopping-cart-postgresql:
    image: 'bitnami/postgresql:15.3.0'
    ports:
      - 35432:5432
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=very-secure-password
      - POSTGRESQL_DATABASE=shopping_cart_db

  warehouse-postgresql:
    image: 'bitnami/postgresql:15.3.0'
    ports:
      - 45432:5432
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=very-secure-password
      - POSTGRESQL_DATABASE=warehouse_db

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka-server-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092, PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  product-quantity:
    build:
      context: ./server/ProductQuantityService/
    depends_on:
      - warehouse-postgresql
    ports:
      - 5164:80
    environment:
      ASPNETCORE_ENVIRONMENT: Production

#  frontend:
#    image: node:18-alpine
#    container_name: frontend
#    build:
#      context: ./client/
#    ports:
#      - '3006:3006'


  backend-shopping-cart:
    image: 'shopping-cart-project:latest'
    build:
      context: ./server/shopping-cart-project
    depends_on:
      - shopping-cart-postgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shopping-cart-postgresql:5432/shopping_cart_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=very-secure-password


#  backend-order:
#    image: 'order-project:latest'
#    build:
#      context: ./server/order-project
#    depends_on:
#      - order-postgresql
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-postgresql:5432/order_db
#      - SPRING_DATASOURCE_USERNAME=user
#      - SPRING_DATASOURCE_PASSWORD=very-secure-password
#
#
#  backend-user:
#    image: 'user-project:latest'
#    build:
#      context: ./server/user-project
#    depends_on:
#      - user-postgresql
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-postgresql:5432/user_db
#      - SPRING_DATASOURCE_USERNAME=user
#      - SPRING_DATASOURCE_PASSWORD=very-secure-password


#  backend-warehouse:
#    image: 'warehouse-project:latest'
#    build:
#      context: ./server/warehouse-project
#    depends_on:
#      - warehouse-postgresql
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://warehouse-postgresql:5432/warehouse_db
#      - SPRING_DATASOURCE_USERNAME=user
#      - SPRING_DATASOURCE_PASSWORD=very-secure-password
