server:
  port: 8092

application:
  environment: local
  environment.name: local


spring:
  application.name: security

  datasource:
    url: jdbc:postgresql://localhost:55432/security_db
    username: user
    password: very-secure-password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl.auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect




